exports.berita_controller = require('./berita_controller')
exports.informasi_desa_controller = require('./informasi_desa_controller')
exports.komentar_controller = require('./komentar_controller')
exports.pengaduan_masyarakat_controller = require('./pengaduan_masyarakat_controller')
exports.pengurus_desa_controller = require('./pengurus_desa_controller')
exports.umkm_controller = require('./umkm_controller')
exports.warga_controller = require('./warga_controller')
exports.pemilihan_ketua_controller = require('./pemilihan_ketua_controller')