exports.berita_controller = require('./berita_controller')
exports.umkm_controller = require('./umkm_controller')
exports.informasi_desa_controller = require('./informasi_desa_controller')
exports.akun_controller = require('./akun_controller')
exports.pemilihan_controller = require('./pemilihan_controller')
exports.pengaduan_masyarakat_controller = require('./pengaduan_masyarakat_controller')